const Icons = {
	Drizzle: require("./animated/rainy-1.svg"),
	"Light Drizzle": require("./animated/rainy-1.svg"),
	"Heavy Drizzle": require("./animated/rainy-1.svg"),
	Rain: require("./animated/rainy-6.svg"),
	"Light Rain": require("./animated/rainy-6.svg"),
	"Heavy Rain": require("./animated/rainy-6.svg"),
	Snow: require("./animated/Blowing_Snow.svg"),
	"Light Snow": require("./animated/snowy-2.svg"),
	"Heavy Snow": require("./animated/Blowing_Snow.svg"),
	"Snow Grains": require("./animated/snowy-4.svg"),
	"Light Snow Grains": require("./animated/snowy-2.svg"),
	"Heavy Snow Grains": require("./animated/Blowing_Snow.svg"),
	"Ice Crystals": require("./animated/rainy-7.svg"),
	"Light Ice Crystals": require("./animated/rainy-7.svg"),
	"Heavy Ice Crystals": require("./animated/rainy-7.svg"),
	"Ice Pellets": require("./animated/rainy-7.svg"),
	"Light Ice Pellets": require("./animated/rainy-7.svg"),
	"Heavy Ice Pellets": require("./animated/rainy-7.svg"),
	Hail: require("./animated/rainy-7.svg"),
	"Light Hail": require("./animated/rainy-7.svg"),
	"Heavy Hail": require("./animated/rainy-7.svg"),
	Mist: require("./animated/Overcast.svg"),
	"Light Mist": require("./animated/Overcast.svg"),
	"Heavy Mist": require("./animated/Overcast.svg"),
	Fog: require("./animated/Overcast.svg"),
	"Light Fog": require("./animated/Overcast.svg"),
	"Heavy Fog": require("./animated/Overcast.svg"),
	"Fog Patches": require("./animated/Overcast.svg"),
	"Light Fog Patches": require("./animated/Overcast.svg"),
	"Heavy Fog Patches": require("./animated/Overcast.svg"),
	Smoke: require("./animated/Overcast.svg"),
	"Volcanic Ash": require("./animated/Overcast.svg"),
	"Widespread Dust": require("./animated/Overcast.svg"),
	Sand: require("./animated/Overcast.svg"),
	Haze: require("./animated/Overcast.svg"),
	Spray: require("./animated/rainy-6.svg"),
	"Dust Whirls": require("./animated/Overcast.svg"),
	Sandstorm: require("./animated/Overcast.svg"),
	"Low Drifting Snow": require("./animated/snowy-4.svg"),
	"Low Drifting Widespread Dust": require("./animated/Overcast.svg"),
	"Low Drifting Sand": require("./animated/Overcast.svg"),
	"Blowing Snow": require("./animated/Blowing_Snow.svg"),
	"Blowing Widespread Dust": require("./animated/Overcast.svg"),
	"Blowing Sand": require("./animated/Overcast.svg"),
	"Rain Mist": require("./animated/rainy-2.svg"),
	"Rain Showers": require("./animated/rainy-1.svg"),
	"Snow Showers": require("./animated/snowy-3.svg"),
	"Snow Blowing Snow Mist": require("./animated/snowy-5.svg"),
	"Ice Pellet Showers": require("./animated/rainy-7.svg"),
	"Hail Showers": require("./animated/rainy-7.svg"),
	"Small Hail Showers": require("./animated/rainy-7.svg"),
	Thunderstorm: require("./animated/Thunderstorm.svg"),
	"Thunderstorms and Rain": require("./animated/Thunderstorm.svg"),
	"Thunderstorms and Snow": require("./animated/Thunderstorm.svg"),
	"Thunderstorms and Ice Pellets": require("./animated/Thunderstorm.svg"),
	"Thunderstorms with Hail": require("./animated/Thunderstorm.svg"),
	"Thunderstorms with Small Hail": require("./animated/Thunderstorm.svg"),
	"Freezing Drizzle": require("./animated/rainy-6.svg"),
	"Freezing Rain": require("./animated/rainy-6.svg"),
	"Freezing Fog": require("./animated/Overcast.svg"),
	"Patches of Fog": require("./animated/Partly_Cloudy.svg"),
	"Shallow Fog": require("./animated/Partly_Cloudy.svg"),
	"Partial Fog": require("./animated/Partly_Cloudy.svg"),
	Overcast: require("./animated/Overcast.svg"),
	Clear: require("./animated/Clear.svg"),
	"Partly Cloudy": require("./animated/Partly_Cloudy.svg"),
	"Mostly Cloudy": require("./animated/cloudy-day-3.svg"),
	"Scattered Clouds": require("./animated/Mostly_Cloudy.svg"),
	"Small Hail": require("./animated/rainy-7.svg"),
	Squalls: require("./animated/Overcast.svg"),
	"Funnel Cloud": require("./animated/Overcast.svg"),
	"Unknown Precipitation": require("./animated/weather.svg"),
	Unknown: require("./animated/weather.svg"),
}

export default Icons; 