

const Icons = {
	Drizzle: require("./animated/rainy-1.svg"),
	"Light Drizzle": require("./animated/rainy-1.svg"),
	"Heavy Drizzle": require("./animated/rainy-1.svg"),
	Rain: require("./animated/rainy-6.svg"),
	"Light Rain": require("./animated/rainy-6.svg"),
	"Heavy Rain": require("./animated/rainy-6.svg"),
	Snow: require("./animated/Blowing_Snow.svg"),
	"Light Snow": require("./animated/Blowing_Snow.svg"),
	"Heavy Snow": require("./animated/Blowing_Snow.svg"),
	"Snow Grains": require("./animated/snowy-4.svg"),
	"Light Snow Grains": require("./animated/snowy-4.svg"),
	"Heavy Snow Grains": require("./animated/snowy-4.svg"),
	"Ice Crystals": require("./animated/rainy-7.svg"),
	"Light Ice Crystals": require("./animated/rainy-7.svg"),
	"Heavy Ice Crystals": require("./animated/rainy-7.svg"),
	"Ice Pellets": require("./animated/rainy-7.svg"),
	"Light Ice Pellets": require("./animated/rainy-7.svg"),
	"Heavy Ice Pellets": require("./animated/rainy-7.svg"),
	Hail: require("./animated/rainy-7.svg"),
	"Light Hail": require("./animated/rainy-7.svg"),
	"Heavy Hail": require("./animated/rainy-7.svg"),
	Mist: require("./animated/Overcast.svg"),
	"Light Mist": require("./animated/Overcast.svg"),
	"Heavy Mist": require("./animated/Overcast.svg"),
	Fog: require("./animated/Overcast.svg"),
	"Light Fog": require("./animated/Overcast.svg"),
	"Heavy Fog": require("./animated/Overcast.svg"),
	"Fog Patches": require("./animated/Overcast.svg"),
	"Light Fog Patches": require("./animated/Overcast.svg"),
	"Heavy Fog Patches": require("./animated/Overcast.svg"),
	Smoke: require("./animated/Overcast.svg"),
	"Volcanic Ash": require("./animated/Overcast.svg"),
	"Widespread Dust": require("./animated/Overcast.svg"),
	// Sand: require("./animated/.svg"),
	// Haze: require("./animated/.svg"),
	// Spray: require("./animated/.svg"),
	// "Dust Whirls": require("./animated/.svg"),
	// Sandstorm: require("./animated/.svg"),
	// "Low Drifting Snow": require("./animated/.svg"),
	// "Low Drifting Widespread Dust": require("./animated/.svg"),
	// "Low Drifting Sand": require("./animated/.svg"),
	// "Blowing Snow": require("./animated/.svg"),
	// "Blowing Widespread Dust": require("./animated/.svg"),
	// "Blowing Sand": require("./animated/.svg"),
	// "Rain Mist": require("./animated/.svg"),
	// "Rain Showers": require("./animated/.svg"),
	// "Snow Showers": require("./animated/.svg"),
	// "Snow Blowing Snow Mist": require("./animated/.svg"),
	// "Ice Pellet Showers": require("./animated/.svg"),
	// "Hail Showers": require("./animated/.svg"),
	// "Small Hail Showers": require("./animated/.svg"),
	// Thunderstorm: require("./animated/.svg"),
	// "Thunderstorms and Rain": require("./animated/.svg"),
	// "Thunderstorms and Snow": require("./animated/.svg"),
	// "Thunderstorms and Ice Pellets": require("./animated/.svg"),
	// "Thunderstorms with Hail": require("./animated/.svg"),
	// "Thunderstorms with Small Hail": require("./animated/.svg"),
	// "Freezing Drizzle": require("./animated/.svg"),
	// "Freezing Rain": require("./animated/.svg"),
	// "Freezing Fog": require("./animated/.svg"),
	// "Patches of Fog": require("./animated/.svg"),
	// "Shallow Fog": require("./animated/.svg"),
	// "Partial Fog": require("./animated/.svg"),
	Overcast: require("./animated/Overcast.svg"),
	Clear: require("./animated/Clear.svg"),
	"Partly Cloudy": require("./animated/Partly_Cloudy.svg"),
	"Mostly Cloudy": require("./animated/Mostly_Cloudy.svg"),
	// "Scattered Clouds": require("./animated/.svg"),
	// "Small Hail": require("./animated/.svg"),
	// Squalls: require("./animated/.svg"),
	// "Funnel Cloud": require("./animated/.svg"),
	// "Unknown Precipitation": require("./animated/.svg"),
	// Unknown: require("./animated/.svg"),
}

export default Icons; 